### ISSUE TITLE
Cannot use backend

### ISSUE THREAD

**Issue by raphink** [voxpupuli/hiera-eyaml-gpg#20]
Hello,

I'm trying to use the gpg backend with hiera-eyaml 2.0.3. The libs are packaged as debs (generated from the published gems):

```
$ dpkg -l | grep hiera-eyaml
ii  hiera-eyaml                              2.0.3-1                       all          OpenSSL Encryption backend for Hiera
ii  ruby-hiera-eyaml-gpg                     0.4-0c2c1                     all          Encryption plugin for hiera-eyaml backend for Hiera
$ eyaml encrypt -n gpg -s "A secret string to encrypt" 
[hiera-eyaml-core] !!! No recipients provided, don't know who to encrypt to
[hiera-eyaml-core] ["/usr/lib/ruby/vendor_ruby/hiera/backend/eyaml/encryptors/gpg.rb:104:in `encrypt'", "/usr/lib/ruby/vendor_ruby/hiera/backend/eyaml/subcommands/encrypt.rb:79:in `execute'", "/usr/lib/ruby/vendor_ruby/hiera/backend/eyaml/CLI.rb:45:in `execute'", "/usr/bin/eyaml:12:in `<main>'"]
$ eyaml encrypt -n gpg -s "A secret string to encrypt" --recipients "xxx@xxx.com"
Error: unknown argument '--recipients'.
Try --help for help.
$ eyaml encrypt -n gpg -s "A secret string to encrypt" --gpg_recipients "xxx@xxx.com"
Error: unknown argument '--gpg_recipients'.
Try --help for help.
$ eyaml encrypt -n gpg -s "A secret string to encrypt" --gpg-recipients "xxx@xxx.com"
Error: unknown argument '--gpg-recipients'.
Try --help for help.
```

I've also tried adding `recipients` or `gpg_recipients` settings to `~/.eyaml/config.yaml`, to no avail.

**Comment by ghoneycutt** [comment]
Closing since it is almost five years old and it seems to work for @andrekeller. Please re-open if this is still an issue.
